spring.application.name=backend

server.port=${PORT:8080}

groq.api.key=${GROQ_API_KEY}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
aws.region=ap-south-1