spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/jansevai
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

grok.api.key= ${GROQ_API_KEY}

server.port=8080